apiVersion: v1
kind: Service

metadata:
  name: hello-devops-service

spec:
  type: NodePort

  selector:
    app: hello-devops-app

  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080